name: Terraform Plan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init
        working-directory: ./infrastructure/main

      - name: Plan
        run: terraform plan
        working-directory: ./infrastructure/main
