name: Terragrunt Plan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read 
  id-token: write

env:
  tf_version: '1.9.2'
  tg_version: '0.63.3'
  working_dir: 'infrastructure/live/'


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{env.tf_version}}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{vars.ACTIONS_ROLE}}  #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-central-1

      - name: Init
        run: terragrunt run-all init

      - name: Plan
        run: terragrunt run-all plan

